name: "Deploy"

on:
    push:
        branches: ["master"]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "Hacemos pull del codigo"
            - run: echo "Correr migraciones"
            - run: echo "Generar Binario"
            - run: echo "Publicar version"